### ISSUE TITLE
Add local config that importers can refer to for correct contents.

### ISSUE THREAD

**Issue by adam-coster** [bscotch/stitch#23]
While the Stitch CLI provides lots of options to fine-tune exactly what gets imported from a project, this always has to be done at the CLI level. Even the simplest imports require a pretty verbose command, so it is not easy to use. Also, project authors have no way of indicating which subset of the project should be imported.

Some sort of config file could be used on both the imported and importing projects to control the parameters in a stable, simpler way. That way an import command without options could default to the config file.

The first step of this would be a config file that a project author can specify to make it easier for that project to be imported into other projects.

Something like:

```yml
# @file stitch-import.yml

project:
  name: My Rad Project
  path: relative/path/to/project/folder
  options:
    # The non-default CLI options that would allow for proper import of this project...
```

Then the Stitch importer would be updated to allow for CLI args to be absent if such a file exists.
